# Generated by Django 4.2.27 on 2026-01-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
